# Usamos la imagen oficial de Node
FROM node:24

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiamos package.json y package-lock.json
COPY package*.json ./

# Instalamos dependencias
RUN npm install

# Copiamos el resto del proyecto
COPY . .

# Exponemos el puerto del backend
EXPOSE 3000

# Comando para iniciar el servidor
CMD ["npm", "run", "dev"]
